# Generated by Django 6.0 on 2025-12-27 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractormodel',
            name='brochure_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tractors/brochures/'),
        ),
        migrations.AddField(
            model_name='tractormodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tractormodel',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='tractors/hero/'),
        ),
        migrations.AddField(
            model_name='tractormodel',
            name='short_summary',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.CreateModel(
            name='SpecGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_groups', to='catalog.tractormodel')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpecItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
                ('value', models.CharField(max_length=240)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.specgroup')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
